# Setup
title:               Soy-A's WILT
description:         'What I Learned Today'
url:                 https://soy-a.github.io
baseurl:             ''

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# About/contact
author:
  name:              Soy-A
  url:               https://github.com/soy-A
  email:             soyeonminn@gmail.com

# Build settings
markdown:            kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:          _sass
  style:             compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:           /:year-:month-:day/:title
paginate:            5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus settings
disqus:              https-soy-a-github-io
