# Setup
title:               Soy-A's WILT
tagline:             'What I Learned Today'
description:         '오늘 배운 것들을 기록합니다'
url:                 https://soy-a.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Soy-A
  url:               https://github.com/soy-A
  email:             soyeonminn@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Disqus settings
disqus:
  shortname: https-soy-a-github-io
